version: '2.1'
services:
  verdaccio:
    image: verdaccio/verdaccio:4.x-next
    container_name: npm-local-registry
    restart: always
    ports:
      - "80:4873"
    volumes:
      # - "./storage:/verdaccio/storage"
      - "./conf:/verdaccio/conf"
#volumes:
#  verdaccio:
#    driver: local
